# Generated by Django 6.0.2 on 2026-02-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('image_name', models.CharField(blank=True, max_length=225)),
                ('image_path', models.CharField(blank=True, max_length=500)),
                ('prediction_class', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('extra_info', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
